//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Mvc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDBan
    {
        public string SoHDBan { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDonBan HoaDonBan { get; set; }
    }
}
