//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Mvc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.ChiTietHDBans = new HashSet<ChiTietHDBan>();
            this.ChiTietHDNhaps = new HashSet<ChiTietHDNhap>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaLoai { get; set; }
        public string MaKhoiLuong { get; set; }
        public string MaHangSX { get; set; }
        public string MaCL { get; set; }
        public string MaCongDung { get; set; }
        public string MaMua { get; set; }
        public string MaMau { get; set; }
        public string MaNuocSX { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public Nullable<System.DateTime> TGBaoHanh { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        public virtual CongDung CongDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDBan> ChiTietHDBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDNhap> ChiTietHDNhaps { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual KhoiLuong KhoiLuong { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual Mua Mua { get; set; }
        public virtual NuocSanXuat NuocSanXuat { get; set; }
    }
}
