//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Mvc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public string SoHDBan { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaKhach { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual ChiTietHDBan ChiTietHDBan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
