//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Mvc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        public string SoHDNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNCC { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ChiTietHDNhap ChiTietHDNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
