//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Mvc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public long roleid { get; set; }
    
        public virtual role role { get; set; }
    }
}
